### ISSUE TITLE
Überworfene Würfe zählen mit ins Average (Average Berechnung korrigeiren)

### ISSUE THREAD

**Issue by rklimpel** [rklimpel/Dartenbank-Public-Board#17]
* Thema für #11

**Comment by dersleeper** [comment]
Sollten nicht generell alle Würfe unter 100 oder so beim Average nicht mehr zählen? Weil man dann potentiell anfängt double out vorzubereiten?

**Comment by rklimpel** [comment]
Würde ich eher als separate Statistik einführen. Ich weiß ehrlich gesagt nicht wie beim Darts offiziell das Average berechnet wird, das müsste man nochmal rausfinden 😄

**Comment by rklimpel** [comment]
https://darthelp.com/guides/how-to-calculate-your-darts-average/


Korrekte Brechnung funktioniert wie folgt:

(Score / Darts) *3

**Comment by rklimpel** [comment]
https://www.reddit.com/r/Darts/comments/snqjyy/question_when_you_bust_with_the_first_dart_of_a/

Busted Turns scheinen als volle 3 Darts gezählt zu werden.

**Comment by rklimpel** [comment]
![Image](https://github.com/user-attachments/assets/69d115ae-2694-4e38-af71-dc5361496115)

Average Veränderung nach dem release der neuen Berechnung (Beispiel Adrian)
