### ISSUE TITLE
Letzte Spieleinstellungen als Vorschlag bei der Spielerstellung

### ISSUE THREAD

**Issue by rklimpel** [rklimpel/Dartenbank-Public-Board#8]
Wenn man ein neues Spiel anlegt, sollen einem die Einstellungen aus dem letzten von mir erstellten Spiel vorgeschlagen werden damit sie automatisch übernommen werden können.

**Comment by dersleeper** [comment]
Find ich gut. Aber eine low hanging fruit und vielleicht leichter zu implementieren wären erstmal überhaupt default values?
 legs = 1, punkte 501, double out usw usw

Wobei der implementationsaufwand letztlich kaum sich unterscheiden dürfte?
